# apps/kasten-config/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ataha/gitops-infra.git
    targetRevision: main
    path: apps/kasten-config
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kasten-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true