---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k10-backups-secret
  namespace: kasten-io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  encryptedData:
    aws_access_key_id: AgBfAJvqEyUI6ML7LBq0lIO7PijNKD8AWiyBROPVvJeWaG624PgZbh89j/LBQ4oAa0j5WYvEX9y4Wk/mPiZVRLE3NjePZyhnCJYVNxZqctVkIQm3fqTWxXEBJv5srMzsPGW9FTCO8UXS3+K9EPCaBavzA597KEhfBhdPqJ/x8TbeYgvnBQITW/jH6FFXTDwr/Z6rfIP/3eFWZGQNl4ExYm+wqDbsh5vUTHvjlIlEEI9hvOyBBJF52BAT3FAMxLUEkpULn+pFdcE1C980MxxSAfuaGsvtQKGEyhIgbnpGoUPTsVkio4j5ejkYnqGEf2p58FTA4DmJPHLHFSgqDkk/zEdd0vj08EY1ZuvR+v/8zro8pozQzyJ0LB34WkR2x+T3F9YWn2Z+AU96p3FeFRYGHn+HpZvv0bs0yQr4IRat4TaA6ua8Sj7R9C/o/uDNJrKUr7j2wq0mDjEGsKFnHKzQM0ViWQ2ArbLpMarD1TdjLaG8TdwO0nINrQFT3vp2xnnB9oHSXAVm/D/kUNbEq2iDjYqtSHMUFzC+KMLqfApOJWlgwTetb0/aDtK3uEZQs5aNRlIMyDXtWsvX4VPxry1U77RX3AOC112lq6Whfp7cSEoLnJvsoCWM5luNqXUxnvWvY/NsCCFggzfRA0htfAegV+uG2XpFD4FgFPFRAaaNAB7I54IBjOe9pNiTyXvbmCanTQrh5MoRdo9uvGRviwo7gwKIhnFrlw==
    aws_secret_access_key: AgA9umpLwLXO1fLvb+3f0Jw8XIE5UHyuil3oF6oW/ZDF2hCc5EsakMUcFBL/Kbu+IMWW81W0Ei/nFCyltVo2f6zk16A60lIcQrFKfPBHEIwLxtKaL1mq4ccH0RRdgCf9sXJdzO9FzWfNcUbT6uUky9EAeG17leDhKup+pcIpHjcNA9r3dujDt8ctt4HHrLRw07kFIPM6FtJkJc47kGZ5qy1lcA+lcgbX5YOGD3TRLin4behNf0VugSUH3qxAndcvughcGWPFX/zr36NtrXaB9SaWhszNh0b2t/tPoA1DQH60sUxN2FVZTZDIUypkk6WbrxEfOLSqV7lz4FwgRb5bGIePNrWxDBaT2gJhPFP7OIQlvouTsw/UbpZDdLRT0hKJc1KqY6OopeGCOV4bSfsbQkqJZzwOd7DsKL5JWvXnWTF0X/AbW4AupgGgNIr+k+/HnW7WpuEMELJ0bY62LXxtU4azSyLQkDQmbhU4bm+Gd4gjm7IYnPAIiVhBq5Vtf1xOA/v+gvEfRJzKWHaxpbAQ1H7mIjAMM8DS9pgEfX4YdLvX87sosaoWqtOb2ewv0JxR46u64u3WmkdM9zuBRW9rYuj5wWcHCOlYGzpM/BfGeUJPUZdz2PvRbNpwWMJRpg1VyA7eUwbs2EFqAmBjxDx+bWxUyri9cncAndTx3lqjncxxPKfhXruHelWwwy2QRDrPE5WYPYNqNnjgE+wGZj14gcd6n2sKJ3bpB+zMfruW9cLx7fmCYsgwrBJr
  template:
    metadata:
      name: k10-backups-secret
      namespace: kasten-io
