---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k10-dr-secret
  namespace: kasten-io
spec:
  encryptedData:
    key: AgCwvgKdVlgy01iz+UR2MfwQdMq8pF+/79vR2xXQ1SXKVGR5fgPQaQL4qMYZszseJ4HibyjUtKJ2AmXYPxgTF8Zvig07rRUDphJfUVdMhdYPLAyeFakH3COipJ/gNA0Aiztv/ILGY+ez7/DxzSuovmwk4s8y5gKwHaE/ApzEE/A9rVyk3JhU98OpwUcVXQ2paBpjAjFiH4v4fP7exMOCes1AQI9/K9tVgn01LbgoiysDBmW+lDzr6ANMelfyco7IOtZWzR4EkY/lnevMOKy4ffB/eIxPbdeqx9nWDtpn6Jm2zcLNAYvtFFkVGT/J0EowO7Slo6bXPKQeo6Hy1Co76Rk66KO6BhKThzqYoeQ92n3vx41bkCswuwM2Bcoc2YHcmcms+P98pfo3yDJQReKYbCsgay4LElbUoLZeypkTpaQ10AmoXdUCO0dd9I+OCBa4CVqZ3wP4yST1Y8dijyyur/ftD0SMYkM1LjAzXABOzKyqIchNesddsgX0w6wTFjiH5G4uzyBzEwnT75YqcOWytXJDrLGntlhpw0evftCk43DT8F4PWRlztHLMj+07OYbrqpZO5OiUQhsJohZfFJ3xCcGz3QYNqL9Mt51MxCsfYyFPdcbtZZkuGaIOTOX97p7oAmbTBZdqlDC0EM7rACVcTIqRbT6XWK5FuXJrX7wjmR1QgB6m94RH+N4Eit88ZZKw5sp2Js1xJD62
  template:
    metadata:
      name: k10-dr-secret
      namespace: kasten-io
