---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k10-backups-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgB3TP+BMGyzkzRmehqI9eMJfOvCKNC0VNUVkMzMf4L7uriYAsF6ve5OJ01AnPAdbSEsvDEp/TeIP7T2SL6ribDT+qNcbD/Yu2p7Nx5xGRFjozpbYsiX36u8oRZ+XMy9XYWhVEvgANMBbnXAQxh3knj3/iB7pUcj4ryLSa8nLeH3miDEcxSLHapW8Nw7+kfg2w9G+uORWX0IMVyc4BTkNXe1eGmvZDzRcBBBnjiYv8pIRKxnu59VcnFEAONINTzTEz4TfL8tu0MKh/OebLtwo2y8Jp4OgvMxTXOT+4Xi/QKqVtiz0Qq3Y1Z7hapVSj7lnO46mL90TENJrB3KpTSdsxHJoSp3m6VN/BbvdGTrb9GcRil5OuCDmiOSEvw6fLW3DF7fVo9h87UDmd8Zhk3T7e3twFJt4jy21eqF+5JgVku2kUdJMiu0lbaRv65ZwQLcDsDIeAIFnaHDWfdaVcQKzC3uVUpvc3Y0uTjWer7/6Zf1jw77NB1Ldo7G5NrvgGXM6LUUILDJece7szQYZcGGSs2aHhXiXZHgK7nAYC5HxIPEUEd4WkqIwUZH7dARwvXhcibL/0OxPnwrZ/yUn59+5bWqXEQGn9vfWSt5Bh2DxFkvn8R5bVe9ihvmWBhc48OyusUn5ls5sui+kx0Jzyrm2ztBbjJLUxuIu8Qy4QBIaSQYyAYzJ6mew+8s54Uwcd7/+oE03CamoYrDncBnUlWZGO1ac28vdQ==
    aws_secret_access_key: AgCtWGP2enli3AXKCOO07RUohFtBdcs1PsZ6hfysAJR2UDvo951uQjdiN4q4aMTnRTtBmNxSqtAHHwTO+/xHaYwsYfMfREqhLU7EWziTgy5Xij5rXNkyz3NsD+2fA2zvqUWHIXRC7hxmEd+TNGwLWU4mCikJaz0SdLKVGJLbknsWmn1BfAR7piKfwvpCqiiXzU1Q6i1PpJg4tty8Ra9bYTFuQwQllJBLTmz5gcd6VaiG35Y3fM3q5N3U3k0HhMfVyAl4W4BNoSDaCyhdnFNzIG8KsGbFevhmJXbJusSjReuamOrNdiC14zNusFrA4dxAM3LNwdWhsq/AZcw+VW3Zkf/pa5GS3tN+lJrI2PGm+aqDeoqMuMREmEiQ/l/t5XagoqdKjeIykWGXKBvwAg27ekZalnROmhg7HeBLMZ28EMECLt6txJWiThQc6qkZdeyxw5vfmlDc1CcD8zWYI9qf44/CaDwXWqxwFrhwu+0APZmiweJ/RFVZYe8cfyNKuHg8e0bigZWb+0ZZSbX4ZQSlSsYlo7mftk8rCD3M+71+AhUOnJu4N2ZApQVSblU1ECWq65/uv4v2qV4ocCohdt1iyBnRBoKSqRsNrUxCceHFMmwVF6hozbydH+/ZsqO6XoQKWdl4eWbs5Z2ApRpVEGT7OGiNjxc62l7d/M6RadDwmHT050cZkyNFTs21g2i2gbXEcySzo7c7hBajERTwrsor1lqxmApRrX7kwk0pwUGHizO1PuGeaMx0YLNA
  template:
    metadata:
      name: k10-backups-secret
      namespace: kasten-io
