---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k10-dr-secret
  namespace: kasten-io
spec:
  encryptedData:
    key: AgCOaI8ao1ZQ0S/eT2prtp6nTqkDlq2MN0TRp//j5AE1OtK2J041tG+0m/uAFwXI3qaMWON6Tw1kRNUgHvX9WcEFXLxeHsN5jYqSolzjGkf86VWDo6rk4XzuqRFYaX4UKJ7MAtuv04uJvaX/rbiozJi88cyg52iOJcNWfcsx/ZtP3qBQyBfkm4W5bnvCtg33qADdahT5uYuLeENQCxyjuw1fRuqmSNucK4m/WgqUIOl27ARbiUVx9QiYR1Lx8EijW0bVk9mYkkpWXnSE+xIcYi24aDUrWatnzsHxWltlXXFEB5VvZozlH/3l/18262KWiXRbzn+ptwtevovM+t0yOeyEKaRep2jRF1M8yxU2A5xtNotGIk/iTiwoDYKeCei3jlTRQyuPkzMUtiys1ZL4UbODZWyJJuDD4/u5I+EaK1ToCJazuvCz0wF/ghCJZB1McqC2/hkQcUF5p2zmcf/bLirDqBTGe/4pw8n/anmDGTqw0t2oWNIRHhqQCaUzXw3wAIFisLxV3qxkxMMMD4MZp8K4aYLqiEAOvSYVRKijky7bIf3Sqz8kuzRnoEADRAeSjWvsiL9QF1MdSCfplIrkbVG7HuvvVzqucgFfR28yKYo5W1D3zE5H46HEGoDqxkSf+K5MenzTibNc476TkRb5zGvBQxIHQF9hARYHgPbww1S90z3qi5su4+C1LqsRGfXQtyjRIHvfeAXo
    source: AgAsqRyN41DtlPB6GGrvHDnsYUkOt+Isl0rnZ3YWrMmv9XE/sxmlmEjmIBC33tE9ZM6cbZkeg0MJvJQXO0vNRfD7uc1AGVg4WRNSQ9MUmHUEijz8yl9SFoRu55cOrup/AhWjRQR0FYFcoQj/FhVTtFQQ4pE4qUqCTnNuLdZuVjFtR9BBozB7B6UUFhCLOMT1M+W4iZ9yLqy54pxTMceFEMPpZCesoPko5ZhJtbOjVq+3JyyZw2+oW6AJXDHANTvMmaWy0Pi5Y+H9NUGtS5QRKZRrEbRAIU9xWAjQ/N0Wsao1BTz8As1//ERv+9GoCmRgsElX9+bhL/wfnye0mBJNNQoqldM8OMcuYfWewV24h9uMs80e37cI1VxhFlsnYhf1pn8tYMPaCYQ9KJbcXpWrHtyxVpCJUuYJ7t0P7VYJzf4Qe8Sceavv7lgKr/5JFx1oHvCL9/wx79pkJ01AvS2kP07/bXnqwGN9ldy91/qM9uPx/rkABdhLd7yuktenS7rH2ovR3lQlP2hs2BQ10Yxi0NANsHLXlCgCpYq6KqmauMRzMegQ0sTRa0KTJYFHaBcUsgQYvu0vJkJw4rUt5B+zds9jS47MFDRnBMgSKQat81h99p/cB4rgI3ty6HvhV4M88PCOdHfNCuxpkvqpJ78E+EBxI8xOv7YHELD6g9p2IsYGuX2ND/qCRNmZWgNnnhC8gP9aRV+t
  template:
    metadata:
      name: k10-dr-secret
      namespace: kasten-io
    type: Opaque
